language: python
python:
        - "2.7"
# command to install dependencies
install:
        - cp ./git_ext/static/CONFIG_TEMPLATE.yml ~/.git_ext.yml
        - pip install -r requirements.txt
# command to run tests
script: 
        - python -m pytest tests/
        - codecov
