language: python
python:
        - "2.7"
# command to install dependencies
install:
        - cp ./git_ext/static/CONFIG_TEMPLATE.yml ~/.git_ext.yml
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pytest
        - pip install pytest-cov
# command to run tests
script: 
        - pwd
        - py.test --cov=./
after_success:
        - codecov
