language: python
python:
        - "2.7"
# command to install dependencies
install:
        - cp ./git_ext/static/CONFIG_TEMPLATE.yml ~/.git_ext.yml
        - pip install -r requirements.txt
        - pip install pytest-cov
# command to run tests
script:
        - py.test --cov=git_ext
after_success:
        - codecov
