---
bitbucket:
        email: glenn.lai@bosondata.com.cn
        password: Gm9Knjks6
gitlab:
  domain: ""
  private_token: ""

git_ext:
        logging:
                level: DEBUG
                format: "%(name)s - %(message)s"
